-- Comandos SQL se dividem em duas linguagens
------------------------------------------------
-- DDL (Data Definitions Language)
-- => Comandos de definição do banco de dados
-- Ex. CREATE DATABASE NAME
--     DROP DATABASE
--		CREATE TABLE NAME (COLUNAS)
--		DROP TABLE NAME

-- --------------------------------------------
-- DML (DATA MANIPULATION LANGUAGE)
-- => COMANDOS DE MANIPULAÇÃO DE DADOS
-- Ex. SELECT COLUNAS FROM TABELA
--		INSERT INTO TABELA (COLUNAS) VALUES (VALORES)
--		DELETE FROM FROM TABELA
-- 		UPDATE COLUNAS FROM TABELA